### ISSUE TITLE
Nogui not enabled 

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#8]
![image](https://user-images.githubusercontent.com/18745823/79936420-49272e80-840c-11ea-9772-66388ee24eaf.png)
The server does not launch with nogui, therefore it has a console and GUI. This should be configurable as some people may not want two tabs open to run a single server.

**Comment by KastenKlicker** [comment]
I don't recommend to run a hole server on Windows 24/7. If you want to host a server to actually play online you should switch to a Lunix based system like Ubuntu (Server). It's not as beginnerfriendly like windows, because it works only with a commandline, but you save resources and have better controll over security. I heard from some people, this Installer is greate for plugin testing and they appreciate the GUI, but if there are people who want to chance this I already added a InstallationPDF at the end of the installation to give a little help to change the settings.

**Comment by josephworks** [comment]
Then, could we make nogui configurable through the installer?
